[package]
name = "d"
version = "0.2.0"
authors = ["lightning1141 <lightning1141@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.2.6"
regex = "1.5.6"
anyhow = "1.0.58"
surf = "2.3.2"
async-std = { version = "1.12.0", features = ["attributes"] }
async-process = "1.4.0"
tracing = "0.1.35"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
directories = "4.0.1"
